name: CI/CD EC2
on:
  push:
    branches:
      - master

jobs:
  pipeline-cd:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v1

      - name: upload files ssh
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/node_modules/, /.github/"
      
      - name: Install npm dependencies
        run: npm install

      - name: Restart PM2
        run: pm2 restart index --update-env