name: CI/CD EC2
on:
  push:
    branches:
      - master

jobs:
  pipeline-cd:
    name: Deploy to EC2-
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: install npm
        run: npm ci

      - name: upload files ssh
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/ubuntu/node-app/"
          EXCLUDE: "/dist/, /node_modules/, /.github/"
          
      - name: directory
        working-directory: /home/ubuntu/node-app

      - name: restart PM2
        run: sh deploy.sh
